services:
  nginx:
    logging:
      driver: json-file
  nextjs:
    logging:
      driver: json-file
  spring:
    logging:
      driver: json-file
  fastapi:
    logging:
      driver: json-file
  postgresql:
    logging:
      driver: json-file
